woowa-techcamp-2022/android-repo-02

.idea/misc.xml, presentation/src/main/res/drawable/bg_gradient.xml, presentation/src/main/res/drawable/box_large_button.xml
=> [ADD] #13 - blue button resource

.idea/discord.xml, presentation/build.gradle
=> [ADD] #17 - viewBinding Dependancy

presentation/src/main/java/com/woowahan/repositorysearch/ui/result/ResultActivity.kt, presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/ProfileFragment.kt, presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchFragment.kt, presentation/src/main/java/com/woowahan/repositorysearch/util/FragmentManagement.kt
- ResultActivity Back Button Event 처리
- 프래그먼트 이동 할 때 마다 PageName 변경해주기
=> [FIX] #22 - result activity

presentation/src/main/res/layout/activity_main.xml
=> [REFECTOR] Main 액티비티 네이밍 컨벤션

presentation/src/main/res/layout/activity_result.xml
Result 액티비티의 네이밍 컨벤션을 수정하였습니다.
=> [REFECTOR] #30 - Result 액티비티 네이밍 컨벤션

.idea/misc.xml, presentation/src/main/res/layout/fragment_profile.xml
=> [REFECTOR] #30 - 프로필 프래그먼트 네이밍 컨벤션

presentation/src/main/AndroidManifest.xml
충돌 과정에서 발생한 Manifest 문제 수정
- MainActivity 중복 선언 삭제
- 시작 Activity 및 딥 링크 콜백을 LoginActivity로 변경
=> [FIX] #25 - 시작 Activity를 LoginActivity로 변경

data/src/main/java/com/woowahan/data/auth/AuthRepositoryImpl.kt, data/src/main/java/com/woowahan/data/entity/GitHubTokenData.kt, presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginViewModel.kt
dataSource에서 GitToken mapping
- toModel() extension function
=> [REFACTOR] #36 - Mapping GitToken in  dataSource

presentation/src/main/java/com/woowahan/repositorysearch/ui/main/DividerItemDecoration.kt, presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
NotificationDivider 이름 변경
- NotificationDivider -> DividerItemDecoration
Closes #45
=> [REFACTOR] #45 - rename to dividerItemDecoration

data/src/main/java/com/woowahan/data/entity/UserData.kt, data/src/main/java/com/woowahan/data/user/UserDataSourceImpl.kt, data/src/main/java/com/woowahan/data/user/UserRepositoryImpl.kt, data/src/main/java/com/woowahan/data/user/UserService.kt, domain/build.gradle, domain/src/main/java/com/woowahan/domain/model/Result.kt, domain/src/main/java/com/woowahan/domain/model/User.kt, domain/src/main/java/com/woowahan/domain/repository/UserRepository.kt, domain/src/main/java/com/woowahan/domain/userUseCase/GetUserUseCase.kt, presentation/src/main/java/com/woowahan/repositorysearch/di/module/DataSourceModule.kt, presentation/src/main/java/com/woowahan/repositorysearch/di/module/RepositoryModule.kt, presentation/src/main/java/com/woowahan/repositorysearch/di/module/ServiceModule.kt, presentation/src/main/java/com/woowahan/repositorysearch/di/module/UseCaseModule.kt, presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainActivity.kt, presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainViewModel.kt, presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
=> [ADD] #37 - MainActivity Server

presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainViewModel.kt
- Conflict된 코드 Merge 시 잘못 수정한 코드 존재
- MainViewModel Log Import가 존재하지 않아 오류 발생
- Log 코드를 삭제함으로서 해결
=> [FIX] #48 - MainViewModel

domain/src/main/java/com/woowahan/domain/notificationUseCase/GetNotificationsUseCase.kt, presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt, presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationViewModel.kt
기존 Coroutine 으로 구현된 getNotification 함수를 coroutine flow 를 사용해서 구현
=> [REFACTOR] #52 - change coroutine to coroutine flow in notification

presentation/src/main/AndroidManifest.xml
=> [DEL] #60 - LoginActivity noHistory option

presentation/src/main/res/layout/activity_main.xml
- 메인 액티비티 TabLayout의 마진을 수정했습니다.
=> [REFECTOR] #64 - MainActivity

data/src/main/java/com/woowahan/data/user/UserDataSourceImpl.kt, data/src/main/java/com/woowahan/data/user/UserRepositoryImpl.kt, data/src/main/java/com/woowahan/data/user/UserService.kt, domain/src/main/java/com/woowahan/domain/model/User.kt, domain/src/main/java/com/woowahan/domain/repository/UserRepository.kt, domain/src/main/java/com/woowahan/domain/userUseCase/GetUserUseCase.kt, presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/ProfileFragment.kt
=> [ADD] #58 - profile

presentation/src/main/java/com/woowahan/repositorysearch/di/module/RetrofitModule.kt
Scalar converter 빌드 에러 수정
- RetrofitModule의 scalar converter 제거
=> [DEL] #78 - Remove scalarConverter in RetrofitModule

presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchFragment.kt
Searching 하기 전에 delay 추가
- Timer를 이용해서 입력 후 0.7초 후 검색 api를 보내도록 함
=> [FEAT] #85 - Set 700milisecond before searching

data/src/main/java/com/woowahan/data/entity/GitHubTokenData.kt, domain/src/main/java/com/woowahan/domain/model/GitToken.kt, presentation/build.gradle, presentation/src/main/java/com/woowahan/repositorysearch/di/module/RetrofitModule.kt, presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginActivity.kt, presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainActivity.kt, presentation/src/main/java/com/woowahan/repositorysearch/util/ApiHeaderInterceptor.kt, presentation/src/main/java/com/woowahan/repositorysearch/util/DataStore.kt, presentation/src/main/res/layout/activity_login.xml
로그인 더블 클릭으로 생기는 문제 방지
- Login 버튼 0.3초 이내 클릭할 시에 무시
- 버튼 클릭 직후 로딩창 표시
=> [FIX] #98 login 화면 버그 수정

presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchFragment.kt
=> [FEAT] #110 - Show keyboard in search fragment

presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchFragment.kt
키보드가 바로 안 올라오는 문제 해결
- Keyboard 표시 전 딜레이 추가
=> [FIX] #114 - 키보드 안보이던 버그 해결
